# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TSCslMeVVBLn5Bm6l12axrM_w1z3czHs

**Task 08: Completing missing data**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

for s,r,o in g1:
  print(s,r,o)

for s,r,o in g2:
  print(s,r,o)

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

from rdflib.plugins.sparql import prepareQuery
vcard= Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
ns=Namespace("http://data.org#")
Personas1=[]  #personas en grafo 1. Para estas personas con atributos vacíos en given name, family name y email, rellenaremos datos de g2.

for s,p,o in g1.triples((None,RDF.type,ns.Person)):
  Personas1.append(s)


for persona in Personas1:
  if not list(g1.triples((persona,vcard.Given,None))):
      g1.add((persona,vcard.Given,g2.value(persona,vcard.Given,None)))
  if not list(g1.triples((persona,vcard.Family,None))):
      g1.add((persona,vcard.Family,g2.value(persona,vcard.Family,None)))
  if not list(g1.triples((persona,vcard.EMAIL,None))):
      g1.add((persona,vcard.EMAIL,g2.value(persona,vcard.EMAIL,None)))


for a,b,c in g1:
  print(a,b,c)