# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TSCslMeVVBLn5Bm6l12axrM_w1z3czHs

**Task 08: Completing missing data**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

for s,r,o in g1:
  print(s,r,o)

for s,r,o in g2:
  print(s,r,o)

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

from rdflib.plugins.sparql import prepareQuery
vcard= Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
q = prepareQuery('''
  SELECT 
    ?s ?p ?o
  WHERE { 
    ?s vcard:Given ?o
    
  }
  ''',
  initNs = {"vcard": vcard}
)



for r in g2.query(q):
  g1.add((r.s,vcard.Given,r.o))



q2 = prepareQuery('''
  SELECT 
    ?s ?p ?o
  WHERE { 
    ?s vcard:Family ?o
    
  }
  ''',
  initNs = {"vcard": vcard}
)



for r2 in g2.query(q2):
  g1.add((r2.s,vcard.Family,r2.o))


 
q3 = prepareQuery('''
  SELECT 
    ?s ?p ?o
  WHERE { 
    ?s vcard:EMAIL ?o
    
  }
  ''',
  initNs = {"vcard": vcard}
)



for r3 in g2.query(q3):
  g1.add((r3.s,vcard.EMAIL,r3.o))


for a,b,c in g1:
  print(a,b,c)