# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/DCY1117/Curso2022-2023-ODKG/blob/master/Assignment4/course_materials/notebooks/Task09.ipynb

**Task 09: Data linking**
"""

# pip install rdflib, Terminal
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from typing import Type
from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.plugins.sparql import prepareQuery

from rdflib.namespace import RDF, RDFS, OWL

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

q1 = prepareQuery('''
  SELECT ?Subject ?given ?family WHERE { 
    ?Subject VCARD:Given ?given.
    OPTIONAL{ ?Subject VCARD:Family ?family } 
  } 
  ''',
  initNs = { "VCARD": VCARD }
)

print("Individuos, apodo y nombre de familia grafo 1##############")
for r in g1.query(q1):
  for r1 in g2.query(q1):
    if r.given == r1.given:
      if r.family == r1.family:
        g3.add((r.Subject, OWL.sameAs, r1.Subject))

for subj, pred, obj in g3:
  print("Grafo g3##############")
  print(subj,pred,obj)
  print("Grafo g1##############")
  for s, p, o in g1.triples((subj, None, None)):
    print(s, p, o)
  print("Grafo g2##############")
  for s, p, o in g2.triples((obj, None, None)):
    print(s, p, o)

print("\n\n")
print("Grafo g3##############")
for subj, pred, obj in g3:
  print(subj,pred,obj)