# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BxyCri0V5kSdEgQwUXz8fgXGYv7VO_8q

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

from rdflib.plugins.sparql import prepareQuery
ns = Namespace("http://data.org#")

#get all instances of Person in g1
q1 = prepareQuery('''
  SELECT ?Subject WHERE{
    ?Subject a ?Class .
    FILTER (?Class in (ns:Person))
  }
  ''',
  initNs={"ns" : ns}
)

#visualize graph before additions
for r in (g1.query(q1)):
  for s,p,o in g1.triples((r.Subject, None, None)):
    print(s,p,o)

#for each Person in g1, query g2 for additional fields and add them to g1
fields_final = []

for r in g1.query(q1):
  person = r.Subject
  
  fields = [(s,p,o) for s,p,o in g2.triples((person, None, None))]
  for i in fields:
    fields_final.append(i)

print("---")

for i in range(0, len(fields_final)):
  g1.add((fields_final[i][0], fields_final[i][1], fields_final[i][2]))
  print("ADDED: (", fields_final[i][0], fields_final[i][1], fields_final[i][2], ")")

#no worries about duplicates, thankfully...
#visualize results
print("---")

for r in (g1.query(q1)):
  for s,p,o in g1.triples((r.Subject, None, None)):
    print(s,p,o)
