# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GhwcX1Icuj9Vfpy16dWOre48OKYcaPMk

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib import XSD
from rdflib.namespace import RDF, RDFS, OWL
from rdflib.plugins.sparql import prepareQuery

ns = Namespace("http://data.three.org#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

#Find identities in the 2 graphs:
#1. Get all instances of Person in Graph 1
q1 = prepareQuery('''
                  SELECT ?Subject WHERE{
                    ?Subject a ns:Person
                  }
                  ''', initNs={"ns" : ns}
                  )

#2. For each Person in Graph 1, check Given and Family Name
names_list = []
for r in g1.query(q1):
  given = g1.value(r.Subject, VCARD.Given, None)
  fn = g1.value(r.Subject, VCARD.FN, None)
  names_list.append((r.Subject, given, fn))

#3. For each Person in Graph 1, check if anyone in Graph 2 has the same Given and FN
q2 = prepareQuery('''
                  SELECT ?Subject WHERE{
                    ?Subject VCARD:Given ?Given .
                    ?Subject VCARD:FN ?FN
                  }
                  ''', initNs={"ns" : ns, "VCARD" : VCARD}
                  )

for i in names_list:
  for r in g2.query(q2, initBindings = {'?Given' : Literal(i[1] , datatype=XSD.string), '?FN' : Literal(i[2] , datatype=XSD.string)}):
    #Create triples connecting the identities and insert in g3
    g3.add((i[0], OWL.sameAs, r.Subject))

#Visualize the result
print("GRAPH 3:\n")
for s,p,o in g3:
  print(s,p,o)