# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18P0xTS31q1P7nR4efg0Yy3QrClOxqMAe

**Task 08: Completing missing data**
"""

github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2020-2021/master/Assignment4/"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"resources/data01.rdf", format="xml")
g2.parse(github_storage+"resources/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

ns = Namespace("http://data.org#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

print("g1 before")
for s,p,o in g1.triples((None, RDF.type , ns.Person)):
  for s1,p1,o1 in g1.triples((s, None, None)):
    print(s,p1,o1)
print("g2")
for s,p,o in g2.triples((None, RDF.type , ns.Person)):
  for s1,p1,o1 in g2.triples((s, None, None)):
    print(s,p1,o1)

for s,p,o in g1.triples((None,  RDF.type , ns.Person)):
  for s1,p1,o1 in g2.triples((s,vcard.Given, None )):
    g1.add((s,vcard.Given,o1))
  for s1,p1,o1 in g2.triples((s,vcard.Family, None )):
    g1.add((s,vcard.Family,o1))
  for s1,p1,o1 in g2.triples((s,vcard.EMAIL,None)):
    g1.add((s,vcard.EMAIL,o1))

print("g1 after")
for s,p,o in g1.triples((None, RDF.type , ns.Person)):
  for s1,p1,o1 in g1.triples((s, None, None)):
    print(s,p1,o1)