# Show all the elements in the ontology, including the class each one belongs to:

SELECT DISTINCT ?x ?y
WHERE
{
	?x rtf:type ?y
}

# See all the classes of the ontology

SELECT DISTINCT ?x
WHERE
{
	?x a owl:Class
}

# Count all the classes of the ontology

SELECT COUNT(DISTINCT ?x)
WHERE
{
	?x rtf:type owl:Class
}

# See all the properties of the ontology divided by the type of property

#Datatype properties
SELECT DISTINCT ?data
WHERE
{
	?data rdf:type owl:DatatypeProperty
}

#Object properties
SELECT DISTINCT ?obj
WHERE
{
	?obj rdf:type owl:ObjectProperty
}

# See all the instances of the example (?)

SELECT DISTINCT ?x
WHERE
{
	?x a ?y .
	?x a owl:Class
}

# Show the instances that belong to the class "Establishment" (?)

SELECT DISTINCT ?prop ?y
WHERE
{
	?x a ?Class .
	?x ?prop ?y
}

# Show all cardiology clinics

SELECT ?x
WHERE
{
	?x a ns:Clinic .
	?x ns:typologyOfClinic "Cardiología"^^xsd:string
}