# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_G61ev4hDT9PggzfIXSjREyNDKVFz699

**Task 09: Data linking**"""

github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

from rdflib.plugins.sparql import prepareQuery
from rdflib import FOAF
from rdflib.namespace import OWL
()
ns = Namespace("http://data.org#")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

print("GRAPH 1 - Nicknames")
for s,p,o in g1.triples((None, vcard.Given, None)):
  print (s, p,o)

print("GRAPH 2 - Nicknames")
for s,p,o in g2.triples((None, vcard.Given, None)):
  print (s, p,o)
  
print("GRAPH 1 - Family Names")
for s,p,o in g1.triples((None, vcard.Family, None)):
  print (s, p,o)

print("GRAPH 2 - Family Names")
for s,p,o in g2.triples((None, vcard.Family, None)):
  print (s, p,o)

for s,p,o in g1.triples((None, vcard.Given, None)):
  for a,b,c in g2.triples((None, vcard.Given, None)):
    if c == o:
      for d,e,f in g1.triples((s, vcard.Family, None)):
        for h,i,l in g2.triples ((a, vcard.Family, None)):
          if f == l:
            g3.add((s, OWL.sameAs, a))

print("GRAPH 3")
for s,p,o in g3.triples((None, None, None)):
  print (s, p, o)
