prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix property: <https://www.asociadrid.es/ontology/property#> 
prefix class: <https://www.asociadrid.es/ontology/class#> 
prefix rr: <http://www.w3.org/ns/r2rml#>
prefix rml: <http://semweb.mmlab.be/ns/rml#>

#Show all the properties that can be applied to instances of the created knowledge graph, except rdf:type and rdfs:label

SELECT DISTINCT ?pr WHERE{
?a ?pr ?b.
FILTER(?pr!=rdf:type).
FILTER(?pr!=rdfs:label)
} 

#Show all the different addresses strings, with their zipcode, subdistrict and district where they are

SELECT DISTINCT ?address ?zip_code ?subdistrict ?district WHERE {
	?ac property:complete_address ?address.
    ?ac property:zipcode ?zip_code.
	?ac property:belongsToSubdistrict ?sd.
	?sd property:subdistrict_label ?subdistrict.
	?sd property:belongsToDistrict ?d.
	?d property:district_label ?district}

#Show all the different addresses strings, with their zipcode, subdistrict and district where they are(final assignment version)

SELECT DISTINCT ?address ?zip_code ?subdistrict ?district WHERE {
	?ac schema:address ?address.
    ?ac property:zipcode ?zip_code.
	?ac dasp:barrio ?sd.
	?sd property:subdistrict_label ?subdistrict.
	?sd dasp:distrito ?d.
	?d property:district_label ?district}

#Show all the associations based on Tetuan District with more than 40 affiliates
SELECT ?name ?num WHERE{
?as rdf:type class:Association.
?as property:num_affiliates ?num.
?as property:name ?name.
?as property:hasAnAddress ?a.
?a property:belongsToSubdistrict ?sd.
?sd property:belongsToDistrict <https://www.asociadrid.es/resource/District/tetuan>.
FILTER(?num>40).    
} 

#Show all the associations based on Tetuan District with more than 40 affiliates (final assignment version)
SELECT ?name ?num WHERE{
?as rdf:type class:Association.
?as property:num_affiliates ?num.
?as schema:legalName ?name.
?as schema:location ?a.
?a dasp:barrio ?sd.
?sd dasp:distrito <https://www.asociadrid.es/resource/Distrito/tetuan>.
FILTER(?num>40).    
} 

#Select all associations affiliated to "Federacion De La Comunidad De Madrid De Asociaciones De Padres Y Madres
Del Alumnado 'Francisco Giner De Los Rios'" located north of district "Centro", descendingly ordered by their number of
affiliates

SELECT DISTINCT ?as_name ?num WHERE{
{SELECT (MAX (?val) AS ?max_lat) WHERE{
?as property:belongsToSubdistrict ?sd.
  ?sd property:belongsToDistrict <https://www.asociadrid.es/resource/District/centro>.
?as property:latitude ?val
}}
?as property:affiliatedTo <https://www.asociadrid.es/resource/Federation/federacion_de_la_comunidad_de_madrid_de_asociaciones_de_padres_y_madres_del_alumnado_%22francisco_giner_de_los_rios%22>.
?as property:num_affiliates ?num.
?as property:name ?as_name.
?as property:hasAnAddress ?address.
?address property:latitude ?latitude.
FILTER(?latitude>?max_lat).
} ORDER BY DESC(?num)

#Select all associations affiliated to "Federacion De La Comunidad De Madrid De Asociaciones De Padres Y Madres
Del Alumnado 'Francisco Giner De Los Rios'" located north of district "Centro", descendingly ordered by their number of
affiliates(final assignment version)

SELECT DISTINCT ?as_name ?num WHERE{
{SELECT (MAX (?val) AS ?max_lat) WHERE{
?as dasp:barrio ?sd.
  ?sd dasp:distrito <https://www.asociadrid.es/resource/Distrito/centro>.
?as schema:latitude ?val
}}
?as schema:memberOf <https://www.asociadrid.es/resource/Federation/federacion_de_la_comunidad_de_madrid_de_asociaciones_de_padres_y_madres_del_alumnado_%22francisco_giner_de_los_rios%22>.
?as property:num_affiliates ?num.
?as schema:legalName ?as_name.
?as schema:location ?address.
?address schema:latitude ?latitude.
FILTER(?latitude>?max_lat).
} ORDER BY DESC(?num)