# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b0-gkmaR00INat40sfxw963ijTZqiehW

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
ns=Namespace("http://somewhere#")
VCARD=Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g.namespace_manager.bind('ns', ns, override=False)
g.namespace_manager.bind('vcard', VCARD, override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "Person" with RDFLib and SPARQL**"""

def printSubClassesOf(className):
  for s,p,o in g.triples((None, RDFS.subClassOf, className)):
    print(s)
    printSubClassesOf(s)

# TO DO
# Visualize the results (RDFLib)
printSubClassesOf(ns.Person)

# SPARQL
from rdflib.plugins.sparql import prepareQuery

q1 = prepareQuery('''
  SELECT ?Subject WHERE { 
    ?Subject rdfs:subClassOf+ ns:Person. 
  }
  ''',
  initNs = { "ns": ns} # We do subclassOf+ to consider the full taxonomy (without taking into account the root resource Person)
)

for r in g.query(q1):
  print(r.Subject)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

def printInstancesofTaxonomy(className):
  for instance,p,o in g.triples((None, RDF.type, className)):
      print(instance)
  for s,p,o in g.triples((None, RDFS.subClassOf, className)):
    printInstancesofTaxonomy(s)

# TO DO
# Visualize the results (RDFLib)

printInstancesofTaxonomy(ns.Person)

# SPARQL

q2 = prepareQuery('''
SELECT ?people
WHERE { 
{ ?subclasses rdfs:subClassOf* ns:Person.
  ?people a ?subclasses
 } 
}
  ''',
  initNs = { "ns": ns} # By using the * property path we get both the class Person and its subclasses so no union is needed at the query
)


for r in g.query(q2):
  print(r.people)

"""**TASK 7.3: List all individuals of "Person" and all their properties including their class with RDFLib and SPARQL**

"""

# TO DO
# Visualize the results

def printInstancesAndPropertiesOfTaxonomy(className):
  for instance,p,o in g.triples((None, RDF.type, className)):
    for instance,properties,o in g.triples((instance, None, None)):
      print(instance,properties)
  for s,p,o in g.triples((None, RDFS.subClassOf, className)):
    printInstancesAndPropertiesOfTaxonomy(s)

printInstancesAndPropertiesOfTaxonomy(ns.Person)

# SPARQL

q3 = prepareQuery('''
SELECT ?people ?properties
WHERE { 
{ ?subclasses rdfs:subClassOf* ns:Person.
  ?people a ?subclasses.
  ?people ?properties ?values
 } 
}
  ''',
  initNs = { "ns": ns} #Same usage of *
)

for r in g.query(q3):
  print(r.people, r.properties)