# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VYftDyZ_IO3MXZpvfEVPrkdFHSqgt3N-

**Task 08: Completing missing data**
"""



#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

from rdflib.namespace import RDF, RDFS
from rdflib.plugins.sparql import prepareQuery
from rdflib import XSD

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
ns = Namespace("http://somewhere#")


for (s, p, o) in g1.triples((None, RDF.type, ns.Person)):
  print(s, p, o)
  for (s2, p2, o2) in g2.triples((s, None, None)):
    if s.Given is not None:
      g1.add((s, VCARD.Given, Literal(o2.Given, datatype=XSD.string)))
    if s.EMAIL is not None:
      g1.add((s, VCARD.EMAIL, Literal(o2.EMAIL, datatype=XSD.string)))
    if s.Family is not None:
      g1.add((s, VCARD.Family, Literal(o2.Family, datatype=XSD.string)))

print("\n Completed Graph 1:")
for (s, p, o) in g1.triples((None, None, None)):
  print (s, p, o)
