PREFIX schema: <http://schema.org/>
PREFIX bs: <http://smartbikes.org/ontology/bikeStation#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?location ?commune WHERE {
            ?station schema:id "9020".
            ?station bs:locatedInArea ?location.
            ?location owl:sameAs ?commune;
        }

SELECT ?coordinate ?latitude ?longitude WHERE {
            ?station schema:id "9020".
            ?station schema:geo ?coordinate.
            ?coordinate schema:latitude ?latitude.
            ?coordinate schema:longitude ?longitude;
        }
