PREFIX schema: <http://schema.org/>
PREFIX bs: <http://smartbikes.org/ontology/bikeStation#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?location ?commune WHERE {
            ?station schema:id "9020".
            ?station bs:locatedInArea ?location.
            ?location owl:sameAs ?commune;
        }

SELECT ?coordinate ?latitude ?longitude WHERE {
            ?station schema:id "9020".
            ?station schema:geo ?coordinate.
            ?coordinate schema:latitude ?latitude.
            ?coordinate schema:longitude ?longitude;
        }
##Get close to me station
PREFIX schema: <http://schema.org/>

SELECT ?station ?lat ?long WHERE {
  ?station schema:geo ?geo.
  ?geo schema:latitude ?lat.
  ?geo schema:longitude ?long.
  FILTER(
    (?lat<= "48.87") && (?lat>= "48.86")
    &&
    (?long<= "2.36") && (?long>= "2.35")
  )
}